name: my_flutter_app
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0 # Use the latest stable version
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logos.png
    - assets/logo.png
    - assets/indian.jpg
    - assets/nepali.jpg
    - assets/chinese.jpg
    - assets/italian.jpg
    - assets/sweets.jpg
    - assets/soft_drinks.jpg
    - assets/burger.jpg
    - assets/biryani.jpg
    - assets/butter_chicken.jpg
    - assets/dosa.jpg
    - assets/daalmakhni.jpg
    - assets/paneer tikka.jpg
    - assets/paneer chilly.jpg
    - assets/chanamasala.jpg
    - assets/momo.jpg
    - assets/thukpa.jpg
    - assets/chataamari.jpg
    - assets/selroti.jpg
    - assets/khana set veg.jpg
    - assets/khanaset nonveg.jpg
    - assets/yomari.jpg
    - assets/newari khaja set.jpg
    - assets/parotha.jpg
    - assets/friedrice.jpg
    - assets/springroll.jpg
    - assets/chowmen.jpg
    - assets/manchurian.jpg
    - assets/kung pao chicken.jpg
    - assets/chicken wonton soup.jpg
    - assets/chicken pizza.jpg
    - assets/chicken pasta.jpg
    - assets/spinach spaghetti.jpg
    - assets/spicy spaghetti.jpg
    - assets/pesto pasta.jpg
    - assets/pizza.jpg
    - assets/magherita pizza.jpg
    - assets/lasagna.jpg
    - assets/ravioli.jpg
    - assets/strawberryCake.jpg
    - assets/chocoFudge.jpg
    - assets/redvelvetcake.jpg
    - assets/tiramisu.jpg
    - assets/coke.jpg
    - assets/pepsi.jpg
    - assets/sprite.jpg
    - assets/fanta.jpg
    - assets/mountain dew.jpg
    - assets/black coffee.jpg
    - assets/milk tea.jpg
    - assets/black tea.jpg
    - assets/cappuccino.jpg
    
    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos.png"
  android_icon_scale: 5.0